#pragma once

typedef enum
{
	VECTOR_PRIMITIVE_IMAGE,
	VECTOR_PRIMITIVE_TRIANGLE,
	VECTOR_PRIMITIVE_LINE,
	VECTOR_PRIMITIVE_RECTANGLE,
	VECTOR_PRIMITIVE_CIRCLE,
    VECTOR_PRIMITIVE_COLLECTION,
    PRIMITIVE_CUBE,
    PRIMITIVE_SPHERE,
    PRIMITIVE_TERRAIN,
    PRIMITIVE_COURBE_CATMULLROM,
    PRIMITIVE_COURBE_NURBS,
    PRIMITIVE_COURBE_BEZIERCUBIQUE,
    PRIMITIVE_SURFACE_BEZIERCUBIQUE,
    PRIMITIVE_SURFACE_COONS
}   EnumVectorDrawMode;
